### ISSUE TITLE
pin to ClojureScript version

### ISSUE THREAD

**Issue by swannodette** [bodil/cljs-noderepl#11]
I see you are pinning to a specific version of CLJS, is this necessary?

**Comment by bodil** [comment]
...probably not? :)

**Comment by swannodette** [comment]
k I'll fix and send a pull. I'm finding node-repl very handy these days.

**Comment by bodil** [comment]
OK, I'll await that and make a release. Mind you, Piggieback has the same issue too.

**Comment by swannodette** [comment]
@bodil ok thanks I will check with @cemerick as well.

**Comment by bodil** [comment]
Sorry, got bored waiting for a PR, so ftfy. :)

**Comment by cemerick** [comment]
Piggieback does have a minimum supported ClojureScript dependency, which is indicated in the `project.clj`.  What are the use cases for _not_ declaring a dependency on libraries that one is actually dependent upon?  That can cause a variety of issues; I wouldn't recommend the practice FWIW.

**Comment by swannodette** [comment]
Right sorry I realize that piggieback needs to hook into backend details.
