### ISSUE TITLE
js->clj returns argument when given a JavaScript object

### ISSUE THREAD

**Issue by davidchambers** [bodil/cljs-noderepl#16]
noderepl:

```
$ lein trampoline noderepl
ClojureScript:cljs.user> (def o (clj->js {:foo 42}))
#<[object Object]>
ClojureScript:cljs.user> (js->clj o)
#<[object Object]>
ClojureScript:cljs.user> (identical? o (js->clj o))
#<true>
```

ClojureScript REPL:

```
$ script/repljs
ClojureScript:cljs.user> (def o (clj->js {:foo 42}))
#js {:foo 42}
ClojureScript:cljs.user> (js->clj o)
{"foo" 42}
```

Both REPLs handle arrays correctly:

```
ClojureScript:cljs.user> (-> [1 2 3] clj->js js->clj)
[1 2 3]
```

**Comment by danskarda** [comment]
There is second manifestation of the bug in your transcript. `true` was printed as `#<true>`

I investigated the issue and found that the core problem was re-export of basic types (like Boolean, Object etc) from global to context in node_repl.js. I do not know what was the original reason for reexport, but it was rootcause of your problems and issues like

```
(identical? (type true) js/Boolean)
=> #<false>
```

I will submit the patch in few minutes.
