### ISSUE TITLE
nREPL support for Emacs

### ISSUE THREAD

**Issue by darth10** [bodil/cljs-noderepl#4]
Is it possible to connect to noderepl via emacs nREPL client? If not, that would be a really useful feature :smile:

PS: I'm well aware of the possibility that the author prefers Catnip over Emacs; so maybe a plugin for Catnip then?

**Comment by bodil** [comment]
The author is too smart not to prefer Emacs. :)

While I'd prefer if there was a native nREPL server for ClojureScript, launching it through @cemerick's Piggieback is quite possible. I've put together a 0.1.6 release with some simplified support for that.

**Comment by darth10** [comment]
:+1: will take a look asap
